"""
agent/tools.py — Tool registration.

Imports all tool implementations from the top-level tools/ package and
provides create_tool_registry() for building a project-scoped registry.

Project-local tools (generated by scripts/build_api_tools.py) are
auto-discovered from <project>/.dagi/tools/*.py at registry build time and
registered directly in the visible registry.

Predefined subagent types are auto-discovered from
<project>/.dagi/subagents/<type>/ directories that contain both prompt.md
and subagent_config.yaml. Each becomes a SpawnSubagentTool instance in the registry.
"""
from __future__ import annotations

import importlib.util
import inspect
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from agent.base_tool import BaseTool
from agent.registry import ToolRegistry
from tools.bash import BashTool
from tools.edit import EditTool
from tools.git import (
    GitAddTool,
    GitBranchTool,
    GitCheckoutTool,
    GitCommitTool,
    GitDiffTool,
    GitLogTool,
    GitResetTool,
    GitStatusTool,
)
from tools.find import FindTool
from tools.grep import GrepTool
from tools.read import ReadTool
from tools.skill import SkillTool
from tools.copy import CopyTool
from tools.write import WriteTool

if TYPE_CHECKING:
    from agent.loop import AgentCallbacks, AgentConfig
    from agent.session import SessionTracker

from agent import DAGI_ROOT as _DAGI_ROOT

def _load_subagent_config(subagent_type: str, project_path: Path) -> dict:
    """Read and return .dagi/subagents/<type>/subagent_config.yaml as a dict."""
    for root in [project_path, _DAGI_ROOT]:
        config_path = root / ".dagi" / "subagents" / subagent_type / "subagent_config.yaml"
        if config_path.exists():
            return yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    raise FileNotFoundError(
        f"No subagent_config.yaml found for subagent_type={subagent_type!r}. "
        f"Searched: {project_path / '.dagi' / 'subagents' / subagent_type} "
        f"and {_DAGI_ROOT / '.dagi' / 'subagents' / subagent_type}"
    )


def _tools_from_list(
    tool_names: list[str],
    cwd: Path,
    allowed_roots: list[Path] | None,
    handoff_path: Path | None = None,
) -> list[BaseTool]:
    """Instantiate tools by name for a subagent registry."""
    from tools.web_fetch import WebFetchTool
    from tools.web_search import WebSearchTool
    from tools.escalate_issue import EscalateIssueTool

    registry_map: dict[str, BaseTool] = {
        "read":       ReadTool(cwd=cwd, allowed_roots=allowed_roots),
        "grep":       GrepTool(cwd=cwd, allowed_roots=allowed_roots),
        "find":       FindTool(cwd=cwd, allowed_roots=allowed_roots),
        "write":      WriteTool(cwd=cwd, allowed_roots=allowed_roots),
        "edit":       EditTool(cwd=cwd, allowed_roots=allowed_roots),
        "copy":       CopyTool(cwd=cwd, allowed_roots=allowed_roots),
        "bash":       BashTool(cwd=cwd),
        "web_search": WebSearchTool(),
        "web_fetch":  WebFetchTool(),
    }
    if handoff_path is not None:
        registry_map["escalate_issue"] = EscalateIssueTool(handoff_path=handoff_path)
    result: list[BaseTool] = []
    for name in tool_names:
        tool = registry_map.get(name)
        if tool is not None:
            result.append(tool)
        else:
            print(
                f"[tools] Warning: unknown tool name {name!r} in subagent_config.yaml",
                file=sys.stderr,
            )
    return result


def _discover_subagent_tools(
    cwd: Path,
    config: "AgentConfig",
    callbacks: "AgentCallbacks | None",
    tracker: "SessionTracker | None",
) -> list["BaseTool"]:
    """Scan DAGI_ROOT then cwd for .dagi/subagents/; project types override built-ins by name.

    A valid type directory must contain both prompt.md and subagent_config.yaml.
    Directories missing either file are silently skipped.
    """
    from tools.spawn_subagent import SpawnSubagentTool

    on_event_factory = (
        callbacks.on_subagent_event_factory if callbacks else None
    )

    scan_dirs = [_DAGI_ROOT / ".dagi" / "subagents"]
    if cwd != _DAGI_ROOT:
        scan_dirs.append(cwd / ".dagi" / "subagents")

    tools_by_name: dict[str, BaseTool] = {}
    for subagents_dir in scan_dirs:
        if not subagents_dir.exists():
            continue
        for type_dir in sorted(subagents_dir.iterdir()):
            if not type_dir.is_dir():
                continue
            if not (type_dir / "prompt.md").exists():
                continue
            if not (type_dir / "subagent_config.yaml").exists():
                continue
            type_name = type_dir.name
            try:
                cfg = (
                    yaml.safe_load(
                        (type_dir / "subagent_config.yaml").read_text(encoding="utf-8")
                    ) or {}
                )
                description = cfg.get("description", f"Spawn a {type_name} subagent.")
                tools_by_name[type_name] = SpawnSubagentTool(
                    type_name=type_name,
                    description=description,
                    config=config,
                    on_event_factory=on_event_factory,
                    tracker=tracker,
                )
            except Exception as exc:  # noqa: BLE001
                print(
                    f"[tools] Warning: failed to load subagent type {type_name!r}: {exc}",
                    file=sys.stderr,
                )
    return list(tools_by_name.values())


# ---------------------------------------------------------------------------
# Project-local tool helpers
# ---------------------------------------------------------------------------

def _load_project_tools(project_path: Path) -> list[BaseTool]:
    """Dynamically import BaseTool subclasses from <project>/.dagi/tools/*.py.

    Each .py file in the directory is imported as an isolated module.  Any
    class that subclasses BaseTool (other than BaseTool itself) is instantiated
    and returned.

    Files that fail to import are skipped with a warning on stderr — a bad
    generated file should never prevent the session from starting.

    The DAGI root is added to sys.path before importing so that generated
    files can resolve `from agent.base_tool import BaseTool`.
    """
    tools_dir = project_path / ".dagi" / "tools"
    if not tools_dir.exists():
        return []

    # Ensure DAGI root is importable — generated files reference agent.base_tool
    dagi_root_str = str(_DAGI_ROOT)
    if dagi_root_str not in sys.path:
        sys.path.insert(0, dagi_root_str)

    loaded: list[BaseTool] = []
    for py_file in sorted(tools_dir.glob("*.py")):
        if py_file.name.startswith("_"):
            continue  # skip __init__.py and private helpers
        mod_name = f"_dagi_project_tools.{py_file.stem}"
        try:
            spec = importlib.util.spec_from_file_location(mod_name, py_file)
            if spec is None or spec.loader is None:
                continue
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)  # type: ignore[union-attr]
            for _, obj in inspect.getmembers(module, inspect.isclass):
                if (
                    issubclass(obj, BaseTool)
                    and obj is not BaseTool
                    and obj.__module__ == mod_name
                ):
                    loaded.append(obj())
        except Exception as exc:  # noqa: BLE001
            print(
                f"[tools] Warning: failed to load project tool {py_file.name}: {exc}",
                file=sys.stderr,
            )
    return loaded


def _default_ask_user(question: str, options: list[dict], timeout: "float | None") -> str:  # noqa: ARG001
    """Fallback on_ask_user for tests / headless callers (no callbacks supplied)."""
    return next(
        (o["label"] for o in options if o.get("recommended")),
        options[0]["label"] if options else "",
    )


def create_tool_registry(
    cwd: Path = Path("."),
    allowed_roots: list[Path] | None = None,
    skill_roots: list[Path] | None = None,
    plan_mode: bool = False,
    plan_file: Path | None = None,
    plan_mode_initiated_by: str = "user",
    config: "AgentConfig | None" = None,
    callbacks: "AgentCallbacks | None" = None,
    tracker: "SessionTracker | None" = None,
    memory_root: Path | None = None,
    bash_tool: "object | None" = None,
) -> ToolRegistry:
    """Build a fresh ToolRegistry with all tools bound to *cwd*.

    File-touching tools (read, write, edit, grep, find) are sandboxed to
    *allowed_roots* (defaults to [dagi_root, cwd]). BashTool is excluded
    from path sandboxing by design. If *skills* is provided, a SkillTool
    is registered so the agent can load skill documents on demand.

    When *plan_mode* is True, BashTool is omitted and WriteTool/EditTool are
    registered with *plan_file* as their sole allowed path so the agent can
    only write to the plan document.

    When *config* is provided, web research and file exploration are handled
    by delegate tools that spin up sub-agents. Without *config* (e.g. in
    tests), the raw web_search and web_fetch tools are registered instead.
    """
    if config is not None and config.sandbox_mode:
        effective_roots = None
    else:
        effective_roots = allowed_roots if allowed_roots is not None else [_DAGI_ROOT, cwd]
    reg = ToolRegistry()
    reg.register(ReadTool(cwd=cwd, allowed_roots=effective_roots))
    reg.register(GrepTool(cwd=cwd, allowed_roots=effective_roots))
    reg.register(FindTool(cwd=cwd, allowed_roots=effective_roots))
    if plan_mode:
        if plan_file:
            reg.register(WriteTool(cwd=cwd, allowed_roots=[plan_file]))
            reg.register(EditTool(cwd=cwd, allowed_roots=[plan_file]))
        # BashTool always omitted in plan mode
        from tools.ask_user import AskUserTool
        from tools.plan_mode import ExitPlanModeTool
        from tools.show_plan import ShowPlanTool
        _on_ask = callbacks.on_ask_user if callbacks else _default_ask_user
        interactive = plan_mode_initiated_by == "user"
        reg.register(AskUserTool(on_ask_user=_on_ask, timeout=None if interactive else 60))
        reg.register(ExitPlanModeTool())
        if plan_file:
            reg.register(ShowPlanTool(plan_file=plan_file, callbacks=callbacks, interactive=interactive))
        if skill_roots:
            _effective_memory_root = memory_root or cwd / "dagi-memory"
            reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
            from tools.run_skill_script import RunSkillScriptTool
            reg.register(RunSkillScriptTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT))
        # Direct web tools always available in plan mode
        from tools.web_fetch import WebFetchTool
        from tools.web_search import WebSearchTool
        reg.register(WebSearchTool())
        reg.register(WebFetchTool())
        # Subagents available in plan mode: web_research + explore_files
        if config is not None:
            from tools.spawn_subagent import SpawnSubagentTool
            on_event_factory = callbacks.on_subagent_event_factory if callbacks else None
            for _type in ("web_research", "explore_files"):
                try:
                    cfg = _load_subagent_config(_type, cwd)
                    desc = cfg.get("description", f"Spawn a {_type} subagent.")
                except FileNotFoundError:
                    continue
                reg.register(SpawnSubagentTool(
                    type_name=_type,
                    description=desc,
                    config=config,
                    on_event_factory=on_event_factory,
                    tracker=tracker,
                ))
    else:
        reg.register(WriteTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(EditTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(CopyTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(BashTool(cwd=cwd))
        if bash_tool is not None:
            reg.register(bash_tool)
        reg.register(GitStatusTool(cwd=cwd))
        reg.register(GitDiffTool(cwd=cwd))
        reg.register(GitLogTool(cwd=cwd))
        reg.register(GitBranchTool(cwd=cwd))
        reg.register(GitCheckoutTool(cwd=cwd))
        reg.register(GitAddTool(cwd=cwd))
        reg.register(GitCommitTool(cwd=cwd))
        reg.register(GitResetTool(cwd=cwd))
        from tools.complete_plan import CompletePlanTool
        from tools.plan_mode import EnterPlanModeTool
        reg.register(EnterPlanModeTool())
        reg.register(CompletePlanTool())
        from tools.ask_user import AskUserTool
        _on_ask = callbacks.on_ask_user if callbacks else _default_ask_user
        _ask_timeout = (
            config.ask_user_timeout
            if (config and config.ask_user_timeout is not None)
            else 300
        )
        reg.register(AskUserTool(on_ask_user=_on_ask, timeout=_ask_timeout))
        if config is not None and (config.advanced_config is not None or config.worker_config is not None):
            from tools.switch_model import SwitchModelTool
            reg.register(SwitchModelTool())
        from tools.reload_skills import ReloadSkillsTool
        reg.register(ReloadSkillsTool())
        from tools.emote import EmoteTool
        _on_emote = callbacks.on_emote if callbacks else None
        reg.register(EmoteTool(on_emote=_on_emote))
        if config is not None:
            # Auto-discover predefined subagent types from .dagi/subagents/
            # A valid type directory must contain both prompt.md and subagent_config.yaml.
            for spawn_tool in _discover_subagent_tools(
                cwd=cwd, config=config, callbacks=callbacks, tracker=tracker,
            ):
                try:
                    reg.register(spawn_tool)
                except Exception as exc:  # noqa: BLE001
                    print(
                        f"[tools] Warning: could not register subagent tool "
                        f"{spawn_tool.name!r}: {exc}",
                        file=sys.stderr,
                    )

            # Timeout extension for in-flight subagents
            from tools.extend_timeout import ExtendSubagentTimeoutTool
            reg.register(ExtendSubagentTimeoutTool())

            # Custom dynamic subagent (escape hatch — full registry)
            from tools.cli_subagent import SpawnCliSubagentTool
            _cli_on_event_factory = callbacks.on_subagent_event_factory if callbacks else None
            reg.register(SpawnCliSubagentTool(
                project_path=cwd,
                on_event_factory=_cli_on_event_factory,
                tracker=tracker,
            ))

            # Load project-local API tools generated by scripts/build_api_tools.py
            for pt in _load_project_tools(cwd):
                try:
                    reg.register(pt)
                except Exception as exc:  # noqa: BLE001
                    print(
                        f"[tools] Warning: could not register project tool "
                        f"{pt.name!r}: {exc}",
                        file=sys.stderr,
                    )

            if skill_roots:
                _effective_memory_root = memory_root or cwd / "dagi-memory"
                reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
                from tools.run_skill_script import RunSkillScriptTool
                reg.register(RunSkillScriptTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT))

            # Schedule management tools — interactive sessions only.
            # Autonomous tasks (plan_mode_initiated_by == "dagi") cannot see or
            # call these, preventing self-modification of the schedule.
            if plan_mode_initiated_by == "user":
                from tools.schedule_tools import (
                    ListScheduledTasksTool,
                    RemoveScheduledTaskTool,
                    ScheduleTaskTool,
                )
                _sched_path = cwd / ".dagi" / "scheduler" / "schedule.yaml"
                _runs_path = cwd / ".dagi" / "scheduler" / "runs.jsonl"
                reg.register(ScheduleTaskTool(schedule_path=_sched_path))
                reg.register(ListScheduledTasksTool(
                    schedule_path=_sched_path, runs_path=_runs_path,
                ))
                reg.register(RemoveScheduledTaskTool(schedule_path=_sched_path))
        else:
            # Fallback for callers that do not supply config (e.g. tests)
            from tools.web_fetch import WebFetchTool
            from tools.web_search import WebSearchTool
            reg.register(WebSearchTool())
            reg.register(WebFetchTool())
            if skill_roots:
                _effective_memory_root = memory_root or cwd / "dagi-memory"
                reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
        if config is not None and config.tools is not None:
            reg.filter_to(config.tools)
    return reg


def build_subagent_registry(
    subagent_type: str,
    config: "AgentConfig",
    project_path: Path,
    plan_file: Path | None = None,
    callbacks: "AgentCallbacks | None" = None,
    tracker: "SessionTracker | None" = None,
    memory_root: Path | None = None,
    handoff_path: Path | None = None,
) -> ToolRegistry:
    """Build a restricted ToolRegistry for a typed terminal subagent.

    Called by the subprocess (cli.py --subagent-type) to reconstruct the
    tool scope defined in .dagi/subagents/<type>/config.yaml.

    The "custom" type is handled explicitly:
      - "custom": full scope (used by SpawnCliSubagentTool)

    Args:
        subagent_type: Type name matching a .dagi/subagents/<type>/ directory,
                       or "custom" for full-scope dynamic subagents.
        config:        Resolved AgentConfig for this subagent.
        project_path:  Project root; used for cwd and allowed_roots.
        plan_file:     Unused; kept for signature compatibility.
        callbacks:     Subprocess-side callbacks.
        tracker:       Optional session tracker.
        memory_root:   Resolved memory root; used when subagent_config.yaml sets
                       `root: memory_root` to restrict file access to the wiki only.
        handoff_path:  Path where this subagent must write its handoff report;
                       threaded to escalate_issue so it knows where to write
                       its sidecar escalation file.
    """
    default_roots: list[Path] | None = None if config.sandbox_mode else [_DAGI_ROOT, project_path]
    reg = ToolRegistry()

    # ── Custom: full scope for dynamic SpawnCliSubagentTool subagents ─────────
    if subagent_type == "custom":
        for tool in _tools_from_list(
            ["read", "grep", "find", "write", "edit", "bash", "web_search", "web_fetch"],
            project_path, default_roots,
            handoff_path=handoff_path,
        ):
            reg.register(tool)
        return reg

    # ── Config-driven: read tools list from subagent_config.yaml ─────────────
    try:
        cfg = _load_subagent_config(subagent_type, project_path)
    except FileNotFoundError:
        raise ValueError(
            f"No subagent_config.yaml found for subagent_type={subagent_type!r}. "
            f"Expected: "
            f"{project_path / '.dagi' / 'subagents' / subagent_type / 'subagent_config.yaml'}"
        )

    # Subagents with `root: memory_root` are restricted to the wiki directory only.
    root_override = cfg.get("root")
    if root_override == "memory_root" and memory_root is not None:
        cwd_for_tools = memory_root
        effective_roots: list[Path] | None = [memory_root]
    else:
        cwd_for_tools = project_path
        effective_roots = default_roots

    tool_names: list[str] = cfg.get("tools", ["read", "grep", "find"])
    for tool in _tools_from_list(
        tool_names, cwd_for_tools, effective_roots, handoff_path=handoff_path
    ):
        reg.register(tool)
    return reg
