"""
agent/tools.py — Tool registration.

Imports all tool implementations from the top-level tools/ package and
provides create_tool_registry() for building a project-scoped registry.

Project-local tools (generated by scripts/build_api_tools.py) are
auto-discovered from <project>/.dagi/tools/*.py at registry build time and
registered directly in the visible registry.
"""
from __future__ import annotations

import importlib.util
import inspect
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from agent.base_tool import BaseTool
from agent.registry import ToolRegistry
from tools.bash import BashTool
from tools.edit import EditTool
from tools.find import FindTool
from tools.grep import GrepTool
from tools.read import ReadTool
from tools.skill import SkillTool
from tools.write import WriteTool

if TYPE_CHECKING:
    from agent.loop import AgentCallbacks, AgentConfig
    from agent.session import SessionTracker

_DAGI_ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# Project-local tool helpers
# ---------------------------------------------------------------------------

def _load_project_tools(project_path: Path) -> list[BaseTool]:
    """Dynamically import BaseTool subclasses from <project>/.dagi/tools/*.py.

    Each .py file in the directory is imported as an isolated module.  Any
    class that subclasses BaseTool (other than BaseTool itself) is instantiated
    and returned.

    Files that fail to import are skipped with a warning on stderr — a bad
    generated file should never prevent the session from starting.

    The DAGI root is added to sys.path before importing so that generated
    files can resolve `from agent.base_tool import BaseTool`.
    """
    tools_dir = project_path / ".dagi" / "tools"
    if not tools_dir.exists():
        return []

    # Ensure DAGI root is importable — generated files reference agent.base_tool
    dagi_root_str = str(_DAGI_ROOT)
    if dagi_root_str not in sys.path:
        sys.path.insert(0, dagi_root_str)

    loaded: list[BaseTool] = []
    for py_file in sorted(tools_dir.glob("*.py")):
        if py_file.name.startswith("_"):
            continue  # skip __init__.py and private helpers
        mod_name = f"_dagi_project_tools.{py_file.stem}"
        try:
            spec = importlib.util.spec_from_file_location(mod_name, py_file)
            if spec is None or spec.loader is None:
                continue
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)  # type: ignore[union-attr]
            for _, obj in inspect.getmembers(module, inspect.isclass):
                if (
                    issubclass(obj, BaseTool)
                    and obj is not BaseTool
                    and obj.__module__ == mod_name
                ):
                    loaded.append(obj())
        except Exception as exc:  # noqa: BLE001
            print(
                f"[tools] Warning: failed to load project tool {py_file.name}: {exc}",
                file=sys.stderr,
            )
    return loaded


def _default_ask_user(question: str, options: list[dict]) -> str:  # noqa: ARG001
    """Fallback on_ask_user for tests / headless callers (no callbacks supplied)."""
    return next(
        (o["label"] for o in options if o.get("recommended")),
        options[0]["label"] if options else "",
    )


def create_tool_registry(
    cwd: Path = Path("."),
    allowed_roots: list[Path] | None = None,
    skill_roots: list[Path] | None = None,
    plan_mode: bool = False,
    plan_file: Path | None = None,
    plan_mode_initiated_by: str = "user",
    config: "AgentConfig | None" = None,
    callbacks: "AgentCallbacks | None" = None,
    tracker: "SessionTracker | None" = None,
    memory_root: Path | None = None,
) -> ToolRegistry:
    """Build a fresh ToolRegistry with all tools bound to *cwd*.

    File-touching tools (read, write, edit, grep, find) are sandboxed to
    *allowed_roots* (defaults to [dagi_root, cwd]). BashTool is excluded
    from path sandboxing by design. If *skills* is provided, a SkillTool
    is registered so the agent can load skill documents on demand.

    When *plan_mode* is True, BashTool is omitted and WriteTool/EditTool are
    registered with *plan_file* as their sole allowed path so the agent can
    only write to the plan document.

    When *config* is provided, web research and file exploration are handled
    by delegate tools that spin up sub-agents. Without *config* (e.g. in
    tests), the raw web_search and web_fetch tools are registered instead.
    """
    effective_roots = allowed_roots if allowed_roots is not None else [_DAGI_ROOT, cwd]
    reg = ToolRegistry()
    reg.register(ReadTool(cwd=cwd, allowed_roots=effective_roots))
    reg.register(GrepTool(cwd=cwd, allowed_roots=effective_roots))
    reg.register(FindTool(cwd=cwd, allowed_roots=effective_roots))
    if plan_mode:
        if plan_file:
            reg.register(WriteTool(cwd=cwd, allowed_roots=[plan_file]))
            reg.register(EditTool(cwd=cwd, allowed_roots=[plan_file]))
        # BashTool always omitted in plan mode
        if plan_mode_initiated_by == "dagi":
            from tools.plan_mode import ExitPlanModeTool
            reg.register(ExitPlanModeTool())
        if plan_mode_initiated_by == "user":
            from tools.ask_user import AskUserTool
            from tools.plan_mode import ExitPlanModeTool
            from tools.show_plan import ShowPlanTool
            _on_ask = callbacks.on_ask_user if callbacks else _default_ask_user
            reg.register(AskUserTool(on_ask_user=_on_ask))
            if plan_file:
                _show_plan = ShowPlanTool(plan_file=plan_file, callbacks=callbacks)
                reg.register(_show_plan)
                reg.register(ExitPlanModeTool(show_plan_tool=_show_plan))
            else:
                reg.register(ExitPlanModeTool())
        if skill_roots:
            _effective_memory_root = memory_root or cwd / "dagi-memory"
            reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
        # Web research — available in plan mode for information gathering
        if config is not None:
            from tools.web_research import WebResearchTool
            reg.register(WebResearchTool(
                config=config, callbacks=callbacks,
                cwd=cwd, allowed_roots=effective_roots, tracker=tracker,
            ))
        else:
            from tools.web_fetch import WebFetchTool
            from tools.web_search import WebSearchTool
            reg.register(WebSearchTool())
            reg.register(WebFetchTool())
    else:
        reg.register(WriteTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(EditTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(BashTool(cwd=cwd))
        from tools.plan_mode import EnterPlanModeTool
        reg.register(EnterPlanModeTool())
        if config is not None and (config.plan_config is not None or config.worker_config is not None):
            from tools.switch_model import SwitchModelTool
            reg.register(SwitchModelTool())
        if config is not None:
            from tools.explore_files import ExploreFilesTool
            from tools.web_research import WebResearchTool

            web_tool = WebResearchTool(
                config=config, callbacks=callbacks,
                cwd=cwd, allowed_roots=effective_roots, tracker=tracker,
            )
            explore_tool = ExploreFilesTool(
                config=config, callbacks=callbacks,
                cwd=cwd, allowed_roots=effective_roots, tracker=tracker,
            )
            reg.register(web_tool)
            reg.register(explore_tool)

            # Load project-local API tools generated by scripts/build_api_tools.py
            for pt in _load_project_tools(cwd):
                try:
                    reg.register(pt)
                except Exception as exc:  # noqa: BLE001
                    print(
                        f"[tools] Warning: could not register project tool "
                        f"{pt.name!r}: {exc}",
                        file=sys.stderr,
                    )

            if skill_roots:
                _effective_memory_root = memory_root or cwd / "dagi-memory"
                reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
                from tools.run_skill_script import RunSkillScriptTool
                reg.register(RunSkillScriptTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT))
        else:
            # Fallback for callers that do not supply config (e.g. tests)
            from tools.web_fetch import WebFetchTool
            from tools.web_search import WebSearchTool
            reg.register(WebSearchTool())
            reg.register(WebFetchTool())
            if skill_roots:
                _effective_memory_root = memory_root or cwd / "dagi-memory"
                reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
    return reg
