"""
agent/tools.py — Tool registration.

Imports all tool implementations from the top-level tools/ package and
provides create_tool_registry() for building a project-scoped registry.

Project-local tools (generated by scripts/build_api_tools.py) are
auto-discovered from <project>/.dagi/tools/*.py at registry build time and
registered directly in the visible registry.

Predefined subagent types are auto-discovered from
<project>/.dagi/subagents/<type>/main.py via import-based discovery.
Each BaseTool subclass found is instantiated and registered.
"""
from __future__ import annotations

import importlib.util
import inspect
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from agent.base_tool import BaseTool
from agent.registry import ToolRegistry
from tools.bash import BashTool
from tools.edit import EditTool
from tools.find import FindTool
from tools.grep import GrepTool
from tools.read import ReadTool
from tools.skill import SkillTool
from tools.copy import CopyTool
from tools.write import WriteTool

if TYPE_CHECKING:
    from agent.loop import AgentCallbacks, AgentConfig
    from agent.session import SessionTracker
    from agent.session_log import SessionLog
    from agent.parent_context import ParentContextProvider

from agent import DAGI_ROOT as _DAGI_ROOT

# Subagent-registry-building helpers live in agent/subagent_tools.py (split out
# to keep this file under the repo's 500-line file cap). Re-exported here so
# existing call sites (e.g. tools/subagent_main.py, archives/cli.py) importing
# build_subagent_registry from agent.tools keep working unchanged.
from agent.subagent_tools import (  # noqa: F401
    _discover_subagent_tools,
    build_subagent_registry,
)


# ---------------------------------------------------------------------------
# Project-local tool helpers
# ---------------------------------------------------------------------------

def _load_project_tools(project_path: Path) -> list[BaseTool]:
    """Dynamically import BaseTool subclasses from <project>/.dagi/tools/*.py.

    Each .py file in the directory is imported as an isolated module.  Any
    class that subclasses BaseTool (other than BaseTool itself) is instantiated
    and returned.

    Files that fail to import are skipped with a warning on stderr — a bad
    generated file should never prevent the session from starting.

    The DAGI root is added to sys.path before importing so that generated
    files can resolve `from agent.base_tool import BaseTool`.
    """
    tools_dir = project_path / ".dagi" / "tools"
    if not tools_dir.exists():
        return []

    # Ensure DAGI root is importable — generated files reference agent.base_tool
    dagi_root_str = str(_DAGI_ROOT)
    if dagi_root_str not in sys.path:
        sys.path.insert(0, dagi_root_str)

    loaded: list[BaseTool] = []
    for py_file in sorted(tools_dir.glob("*.py")):
        if py_file.name.startswith("_"):
            continue  # skip __init__.py and private helpers
        mod_name = f"_dagi_project_tools.{py_file.stem}"
        try:
            spec = importlib.util.spec_from_file_location(mod_name, py_file)
            if spec is None or spec.loader is None:
                continue
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)  # type: ignore[union-attr]
            for _, obj in inspect.getmembers(module, inspect.isclass):
                if (
                    issubclass(obj, BaseTool)
                    and obj is not BaseTool
                    and obj.__module__ == mod_name
                ):
                    loaded.append(obj())
        except Exception as exc:  # noqa: BLE001
            print(
                f"[tools] Warning: failed to load project tool {py_file.name}: {exc}",
                file=sys.stderr,
            )
    return loaded


def _default_ask_user(question: str, options: list[dict], timeout: "float | None") -> str:  # noqa: ARG001
    """Fallback on_ask_user for tests / headless callers (no callbacks supplied)."""
    return next(
        (o["label"] for o in options if o.get("recommended")),
        options[0]["label"] if options else "",
    )


def create_tool_registry(
    cwd: Path = Path("."),
    allowed_roots: list[Path] | None = None,
    skill_roots: list[Path] | None = None,
    plan_mode: bool = False,
    plan_file: Path | None = None,
    plan_mode_initiated_by: str = "user",
    config: "AgentConfig | None" = None,
    callbacks: "AgentCallbacks | None" = None,
    tracker: "SessionTracker | None" = None,
    memory_root: Path | None = None,
    bash_tool: "object | None" = None,
    session_log: "SessionLog | None" = None,
    parent_context: "ParentContextProvider | None" = None,
) -> ToolRegistry:
    """Build a fresh ToolRegistry with all tools bound to *cwd*.

    File-touching tools (read, write, edit, grep, find) are sandboxed to
    *allowed_roots* (defaults to [dagi_root, cwd]). BashTool is excluded
    from path sandboxing by design. If *skills* is provided, a SkillTool
    is registered so the agent can load skill documents on demand.

    When *plan_mode* is True, BashTool is omitted and WriteTool/EditTool are
    registered with *plan_file* as their sole allowed path so the agent can
    only write to the plan document.

    When *config* is provided, web research and file exploration are handled
    by delegate tools that spin up sub-agents. Without *config* (e.g. in
    tests), the raw web_search and web_fetch tools are registered instead.
    """
    if config is not None and config.sandbox_mode:
        effective_roots = None
    else:
        effective_roots = allowed_roots if allowed_roots is not None else [_DAGI_ROOT, cwd]
    reg = ToolRegistry()
    _proj = config.project_path if config else None
    _services = config.services if config else {}
    reg.register(ReadTool(
        cwd=cwd,
        allowed_roots=effective_roots,
        project_path=_proj,
        service_url=_services.get("doc_converter"),
        callbacks=callbacks,
        config=config,
        parent_context=parent_context,
    ))
    reg.register(GrepTool(cwd=cwd, allowed_roots=effective_roots))
    reg.register(FindTool(cwd=cwd, allowed_roots=effective_roots))
    if plan_mode:
        if plan_file:
            reg.register(WriteTool(cwd=cwd, allowed_roots=[plan_file]))
            reg.register(EditTool(cwd=cwd, allowed_roots=[plan_file]))
        # BashTool always omitted in plan mode
        from tools.ask_user import AskUserTool
        from tools.plan_mode import ExitPlanModeTool
        from tools.show_plan import ShowPlanTool
        _on_ask = callbacks.on_ask_user if callbacks else _default_ask_user
        interactive = plan_mode_initiated_by == "user"
        reg.register(AskUserTool(on_ask_user=_on_ask, timeout=None if interactive else 60))
        reg.register(ExitPlanModeTool())
        if plan_file:
            reg.register(ShowPlanTool(plan_file=plan_file, callbacks=callbacks, interactive=interactive))
        if skill_roots:
            _effective_memory_root = memory_root or cwd / "dagi-memory"
            reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
            from tools.run_skill_script import RunSkillScriptTool
            reg.register(RunSkillScriptTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT))
        # Direct web tools always available in plan mode
        from tools.web_fetch import WebFetchTool
        from tools.web_search import WebSearchTool
        reg.register(WebSearchTool())
        reg.register(WebFetchTool())
        # Subagents available in plan mode: web_research + explore_files
        if config is not None:
            _plan_mode_names = {
                "web_research",
                "explore_files",
            }
            for spawn_tool in _discover_subagent_tools(
                cwd=cwd, config=config, callbacks=callbacks,
                tracker=tracker, session_log=session_log, parent_context=parent_context,
            ):
                if spawn_tool.name in _plan_mode_names:
                    try:
                        reg.register(spawn_tool)
                    except Exception as exc:  # noqa: BLE001
                        print(
                            f"[tools] Warning: {spawn_tool.name!r}: {exc}",
                            file=sys.stderr,
                        )
    else:
        reg.register(WriteTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(EditTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(CopyTool(cwd=cwd, allowed_roots=effective_roots))
        reg.register(BashTool(cwd=cwd))
        if bash_tool is not None:
            reg.register(bash_tool)
        from tools.plan_mode import EnterPlanModeTool
        from tools.update_task_status import UpdateTaskStatusTool
        reg.register(EnterPlanModeTool())
        _plan_path = (
            Path(config.active_plan_file)
            if config and config.active_plan_file
            else None
        )
        reg.register(UpdateTaskStatusTool(plan_path=_plan_path))
        from tools.ask_user import AskUserTool
        _on_ask = callbacks.on_ask_user if callbacks else _default_ask_user
        _ask_timeout = (
            config.ask_user_timeout
            if (config and config.ask_user_timeout is not None)
            else 300
        )
        reg.register(AskUserTool(on_ask_user=_on_ask, timeout=_ask_timeout))
        if config is not None and (config.advanced_config is not None or config.worker_config is not None):
            from tools.switch_model import SwitchModelTool
            reg.register(SwitchModelTool())
        from tools.reload_skills import ReloadSkillsTool
        reg.register(ReloadSkillsTool())
        from tools.emote import EmoteTool
        _on_emote = callbacks.on_emote if callbacks else None
        reg.register(EmoteTool(emotes_dir=_DAGI_ROOT / ".dagi" / "emotes", on_emote=_on_emote))
        if config is not None:
            # Auto-discover predefined subagent types from .dagi/subagents/
            # A valid type directory must contain both prompt.md and subagent_config.yaml.
            for spawn_tool in _discover_subagent_tools(
                cwd=cwd, config=config, callbacks=callbacks,
                tracker=tracker, session_log=session_log, parent_context=parent_context,
            ):
                try:
                    reg.register(spawn_tool)
                except Exception as exc:  # noqa: BLE001
                    print(
                        f"[tools] Warning: could not register subagent tool "
                        f"{spawn_tool.name!r}: {exc}",
                        file=sys.stderr,
                    )

            # Timeout extension for in-flight subagents
            from tools.extend_timeout import ExtendSubagentTimeoutTool
            reg.register(ExtendSubagentTimeoutTool())

            # Load project-local API tools generated by scripts/build_api_tools.py
            for pt in _load_project_tools(cwd):
                try:
                    reg.register(pt)
                except Exception as exc:  # noqa: BLE001
                    print(
                        f"[tools] Warning: could not register project tool "
                        f"{pt.name!r}: {exc}",
                        file=sys.stderr,
                    )

            if skill_roots:
                _effective_memory_root = memory_root or cwd / "dagi-memory"
                reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
                from tools.run_skill_script import RunSkillScriptTool
                reg.register(RunSkillScriptTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT))

            # Schedule management tools — interactive sessions only.
            # Autonomous tasks (plan_mode_initiated_by == "dagi") cannot see or
            # call these, preventing self-modification of the schedule.
            if plan_mode_initiated_by == "user":
                from tools.schedule_tools import (
                    ListScheduledTasksTool,
                    RemoveScheduledTaskTool,
                    ScheduleTaskTool,
                )
                _sched_path = cwd / ".dagi" / "scheduler" / "schedule.yaml"
                _runs_path = cwd / ".dagi" / "scheduler" / "runs.jsonl"
                reg.register(ScheduleTaskTool(schedule_path=_sched_path))
                reg.register(ListScheduledTasksTool(
                    schedule_path=_sched_path, runs_path=_runs_path,
                ))
                reg.register(RemoveScheduledTaskTool(schedule_path=_sched_path))
        else:
            # Fallback for callers that do not supply config (e.g. tests)
            from tools.web_fetch import WebFetchTool
            from tools.web_search import WebSearchTool
            reg.register(WebSearchTool())
            reg.register(WebFetchTool())
            if skill_roots:
                _effective_memory_root = memory_root or cwd / "dagi-memory"
                reg.register(SkillTool(skill_roots=skill_roots, dagi_root=_DAGI_ROOT, cwd=cwd, memory_root=_effective_memory_root))
        if config is not None and config.tools is not None:
            reg.filter_to(config.tools)
        if config is not None and config.disabled_tools:
            reg.filter_out(config.disabled_tools)
    # write_handoff is a lifecycle tool, not a general file-write capability.
    # Keep it provider-visible even when config.tools restricts ordinary tools so
    # inherited children can reuse the parent's exact schema without invalidating
    # the warm tool-cache prefix.
    from tools.write_handoff import WriteHandoffTool
    thread_id = str(getattr(tracker, "thread_id", "session"))[:8]
    handoff_path = cwd / ".dagi" / "handoffs" / f"main_{thread_id}.md"
    reg.register(WriteHandoffTool(handoff_path=handoff_path, display_content=True))
    return reg
